version: "3.8"

services:
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./glpi:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
    ports:
      - 8080:80

  php-fpm:
    build: ./php
    restart: always
    volumes:
      - ./glpi:/var/www
    ports:
      - 9090:9000
