version: "3.8"

services:
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - .:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - phpfpm
    ports:
      - 8080:80

  phpfpm:
    build: ./php
    restart: always
    volumes:
      - ./:/var/www
    ports:
      - 9090:9000
