version: "3.8"

services:
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./glpi:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
    ports:
      - 8080:80

  php-fpm:
    build: ./php
    restart: always
    volumes:
      - ./glpi:/var/www
    depends_on:
      - db
    ports:
      - 9090:9000

  db:
    image: mariadb:latest
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=glpitest
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=user
      - MARIADB_PASSWORD=user123
    ports:
      - 3306:3306