FROM php:8.1-fpm-alpine
MAINTAINER Mary
RUN apk update \

&& apk add php81-curl \
php81-fileinfo \
php81-gd \
php81-json \
php81-mbstring \
php81-mysqli \
php81-session \
php81-zlib \
php81-simplexml \
php81-xml \
php81-intl \
php81-dom \
php81-apache2 \
composer \
vim
